### PR TITLE
Added notebook to compare flatmaps of the same volume

### PR DESCRIPTION
**Pull request by MWolfR**
In the notebook we generate several plots that compare our proposed flatmap for mouse Isocortex to the existing solution by the AIBS.

It can in principle be equally used to compare other flatmaps, as long as they flatten the same (or strongly overlapping) voxel volume.

### CODE REVIEW

**Comment by seirios** [comment]
Thanks Michael!
A couple of minor points:

- As this is related to the flatmapping algorithm, can you please rename the directory to `flatmap/notebooks`?
- Is the file `notebooks/structures.json` verbatim from AIBS? If so, I'd rather we don't redistribute that, but instead download it as part of the notebook. Otherwise, if it is derived from an AIBS file, I'd rather have the code to generate this from sources in the notebook.

**Comment by seirios** [comment]
Furthermore, can you please remove cell outputs from the notebook?

**Comment by MWolfR** [comment]
I moved files to "flatmapping". 
I also removed the dependency on structures.json. Now instead a file that can be found with the original article introducing the CCF can be used.
I want to keep the notebook outputs, as it provides the user an idea of what outputs should look like.

**Comment by seirios** [comment]
Could it be that the JSON hierarchy file [1.json](http://api.brain-map.org/api/v2/structure_graph_download/1.json) provided by AIBS can be used instead of having to convert the Excel file from the publication? (Also, I see that the notebook still mentions `structures.json`).

Regarding the notebook outputs, OK, I see your point. Only perhaps you'd like to remove the warning messages to avoid leaking your username and home directory?

**Comment by seirios** [comment]
I found that flatmap paths are available at 10 um [here](https://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/cortical_coordinates/ccf_2017/dorsal_flatmap_paths_10.h5). I think it'd be best to compare the flatmaps at high/native resolution. Can you please give it a try?

**Pull request merged**
